#!/bin/sh
#
# PROVIDE: homebox
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="homebox"
rcvar="homebox_enable"

load_rc_config $name

: ${homebox_enable="NO"}

command="/root/homebox/app/api"
command_args="/root/homebox/data/config.yml"
pidfile="/var/run/${name}.pid"
logfile="/var/log/${name}.log"

procname="${command}"

command_interpreter="/usr/sbin/daemon"

start_cmd="${name}_start"
stop_cmd="${name}_stop"

homebox_start() {
    echo "Starting ${name}."
    echo "$HBOX_STORAGE_DATA"
    echo "$HBOX_MODE"
    echo "$HBOX_STORAGE_SQLITE_URL"
    ${command_interpreter} -o ${logfile} -P ${pidfile} -- ${command} ${command_args}
}

homebox_stop() {
    echo "Stopping ${name}."
    kill -TERM $(cat ${pidfile})
}

run_rc_command "$1"
